// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWOjWIbDkRTttxvyz7PxNmtfduMul3T6s',
    appId: '1:350771774669:web:248c628b8e4d21105f1584',
    messagingSenderId: '350771774669',
    projectId: 'fir-5aaa0',
    authDomain: 'fir-5aaa0.firebaseapp.com',
    databaseURL: 'https://fir-5aaa0-default-rtdb.firebaseio.com',
    storageBucket: 'fir-5aaa0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4rHt6iqxYHCiyl9Ep0YyRBVPMgG-jniA',
    appId: '1:350771774669:android:a118be01edafc2525f1584',
    messagingSenderId: '350771774669',
    projectId: 'fir-5aaa0',
    databaseURL: 'https://fir-5aaa0-default-rtdb.firebaseio.com',
    storageBucket: 'fir-5aaa0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYxrM5l2R85-OzWklwsVShbn5Cf5nkO0o',
    appId: '1:350771774669:ios:083c79d91a7020335f1584',
    messagingSenderId: '350771774669',
    projectId: 'fir-5aaa0',
    databaseURL: 'https://fir-5aaa0-default-rtdb.firebaseio.com',
    storageBucket: 'fir-5aaa0.appspot.com',
    iosBundleId: 'com.example.tris',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYxrM5l2R85-OzWklwsVShbn5Cf5nkO0o',
    appId: '1:350771774669:ios:083c79d91a7020335f1584',
    messagingSenderId: '350771774669',
    projectId: 'fir-5aaa0',
    databaseURL: 'https://fir-5aaa0-default-rtdb.firebaseio.com',
    storageBucket: 'fir-5aaa0.appspot.com',
    iosBundleId: 'com.example.tris',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWOjWIbDkRTttxvyz7PxNmtfduMul3T6s',
    appId: '1:350771774669:web:8076f2e9a23255f55f1584',
    messagingSenderId: '350771774669',
    projectId: 'fir-5aaa0',
    authDomain: 'fir-5aaa0.firebaseapp.com',
    databaseURL: 'https://fir-5aaa0-default-rtdb.firebaseio.com',
    storageBucket: 'fir-5aaa0.appspot.com',
  );
}
